### ISSUE TITLE
Admin: Matched view - ability to updated status and "cancel" matches

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#12]
- Button to click cancel
- When user clicks button prompt: Do you want to delete "host" "guest" "both" "none"
- The non-deleted are returned to status 1 not used - and return as unmatched guests or available hosts.

**Comment by lars-raaum** [comment]
- [ ] Frontend
- [ ] Backend

**Comment by alkemann** [comment]
Solved with 3 links "cancel match", "remove guest from database" and "remove host from database". last two also cancels match.
