### ISSUE TITLE
Purge inactive users

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#15]
A button to purge inactive users where updated is older than 1 year? 6 months?

Email adresses are dumped to a table, so we can follow up "marketing wise"

**Comment by alkemann** [comment]
Har vi noe specs på tidrom og eventuelt hvordan det blir med disse i forhold til soft-hard delete?

**Comment by lars-raaum** [comment]
Make sure we have fresh hosts and that unused hosts receice feedback: 

- Unused host should 60 days after sign up be "soft deleted"
- They should receive an email where they can re-activate as hosts. 
- If they do not act on the email, they are deleted after 30 more days

**Comment by lars-raaum** [comment]
#41 is the same issue, but #41 is as a one time job, this is a permanent fix.

**Comment by lars-raaum** [comment]
EMAIL TEXT:
From name: Kom inn - Lær norsk rundt middagsbordet
From email: kominnoslo@gmail.com
Subject: Vil du fortsatt invitere på middag? Gi oss beskjed!
Hei,

For en stund siden meldte du deg på Kom inn - Lær norsk rundt middagsbordet. Takk for det!

Vi har dessverre ikke funnet match til deg i løpet av denne tiden, men vi håper du fortsatt kunne tenke deg å invitere på middag!

Da trenger du bare å klikke på denne lenken!

Hvis du ikke trykker på linken antar vi at du ikke lenger er interessert og vi vil slette deg.

Kom inn drives på fritiden av en liten gruppe frivillige og vi rekrutterer gjester gjennom å dra på skolebesøk til Voksenopplæringene i Oslo.

Hvert semester har vi flere titalls skolebesøk og matcher flere hundre middager. Vi rekrutterer hele tiden nye gjester og vil ha behov for nye verter. Jo flere verter vi har, jo større sjanse for gode matcher!

Som sagt: Dersom du fortsatt kunne tenke deg å invitere på middag, klikk på denne linken. Dersom du ikke lenger er interessert, trenger du ikke å gjøre noe.

mvh
Kom inn
www.kom-inn.org
https://www.facebook.com/kominnnorge

**Comment by lars-raaum** [comment]
Text OK

**Comment by lars-raaum** [comment]
Wait with deplpoying until we have a new batch of guests. 
Deploy #54 first
