### ISSUE TITLE
Admin view: Show more fields

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#18]
- updated
- phone
- email
- freetext 

Should be shown in admin / matching view.

**Comment by jonolave** [comment]
Suggestion for how to present the information:

![screen shot 2016-10-16 at 11 39 18](https://cloud.githubusercontent.com/assets/5404905/19416612/353c00e6-9395-11e6-8425-57de028e4898.png)

http://kom-inn-admin.webflow.io/

And let's keep everything in English.
