### ISSUE TITLE
Reactivate used hosts that have been to dinner

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#42]
- Select status = 2 
- Send email to reactivate 
- Email includes text and a confirmation link. 
- On click, users record is set to status 1 (active) and updated is set to now()
- User is ideally redirected to confimation page
- Only select hosts
--
EMAIL TEXT:
From name: Kom inn - Lær norsk rundt middagsbordet
From email: kominnoslo@gmail.com
Subject: Vil du invitere på en ny Kom inn-middag?

Hei, 

I 2016 deltok du på Kom inn - Lær norsk rundt middagsbordet. Vi håper det har vært en eller flere hyggelige middager!

Vil du gjøre det igjen?

Hvis du vil invitere til ny middag denne linken http://pro.kom-inn.org 

Da finner vi en ny match til deg! 

Kom inn drives på fritiden av en liten gruppe frivillige og vi rekrutterer gjester gjennom å dra på skolebesøk til Voksenopplæringene i Oslo. I 2016 har vi hatt mange titalls besøk og matchet flere hundre middager. 

Vi er i gang igjen for 2017 - og vi vil rekruttere nye gjester og ha behov for nye verter. Det vil fortsatt kunne ta noen måneder før vi finner en match.

Meld deg på igjen her http://pro.kom-inn.org 

Godt nyttår!

mvh
Kom inn
www.kom-inn.org
https://www.facebook.com/kominnnorge
---
Confirmation page:
Takk for at du har meldt deg på igjen!

**Comment by alkemann** [comment]
please test
