### ISSUE TITLE
Automated flow / description

### ISSUE THREAD

**Issue by alkemann** [lars-raaum/kom-inn#43]
X days after match and match status matched

Send email
With confirmation link a) in contact b) executed c) no response d) not interested 

a) set match status confirmed
b) set match status executed 
c) cancel match and bring host back into pool, delete guest
d) cancel match and bring guest back into pool, delete host

Y days after math and match status matched
Assume that no dinner, bring back into pool / put guest top in queue.

Also, option to set to executed, click give feedback and option to reactivate

Y plus 1h: cancel match

Y days status matched 
Send email to both host and guest / link to set to executed, to send feedback and to reactivate.

**Comment by lars-raaum** [comment]
First iteration is manual trigger in the matches tab. 

Need to define tasks for: 
- Email content
- Landing pages

Then for automation.
