### ISSUE TITLE
Admin: Matchmaking curation feature

### ISSUE THREAD

**Issue by alkemann** [lars-raaum/kom-inn#5]

**Comment by lars-raaum** [comment]
- User selects one user from a list of unmatched guests
- Nearby available hosts are shown in a table on the right
- Nearby available hosts are shown on a google map. 
- User selects the best matching host in the list
  (if time: - User selects the best matching host in the map - selection is marked in list)
- User clicks on connect-button
- Match is stored in match-table

Triggers issues email and SMS #6 #7 

Dependency: #8
