### ISSUE TITLE
Reactivate or purge used people

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#54]
- Used people should 60 days after sign up be "soft deleted"
- They should receive an email where they can re-activate as hosts or guests (what they were)
- If they do not act on the email, they are deleted after 30 more days
--
EMAIL TEXT:
From name: Kom inn - Lær norsk rundt middagsbordet
From email: kominnoslo@gmail.com
Subject: Vil du på en ny Kom inn-middag?
Hei,

For en stund siden meldte du deg på Kom inn - Lær norsk rundt middagsbordet. Vi håper du har vært på én eller flere hyggelige middager!

Hvis du vil bli delta på en ny middag med en annen familie, klikk på denne linken %link%

Hvis du aldri har vært på middag, men fortsatt har lyst, klikk på denne linken: %link%

Kom inn drives på fritiden av en liten gruppe frivillige og vi rekrutterer gjester gjennom å dra på skolebesøk til Voksenopplæringene i Oslo. Dette gjør vi noen ganger i halvåret, så det kan ta noe tid før vi finner en match. Vi finner heller ikke matcher til alle, men jo flere vi har som ønsker å invitere, jo lettere er det å skape gode matcher!

mvh
Kom inn
www.kom-inn.org
https://www.facebook.com/kominnnorge

Confirmation page:
Takk for at du har meldt deg på igjen!

**Comment by alkemann** [comment]
Need to refactor the "feedback" / "reactivate" public view to support both guest and host reactivation.

**Comment by lars-raaum** [comment]
Deploy when we have confirmed dates for recruitment-visits.

Will imply a lot of emails that will be sendt the first time we send the email. Need to check if mailgun will support this or if it will run out of capacity or go into "spam-mode"?
