### ISSUE TITLE
Remind hosts about dinner

### ISSUE THREAD

**Issue by lars-raaum** [lars-raaum/kom-inn#55]
Remind hosts to make appointment. 
- Send email
- Action A: Click to set match as confirmed or executed
- Action B: Click to set match as cancelled, return guests AND hosts to pool?

Add a status for matches: 
- Reminded

FrontEnd on matches:

Klikk-knapp: Remind-submitbutton on each row
Dropdown på matches-oversikten. "Match" "Reminded" "Confirmed" "Executed"

Remind all button next to drop down of matches:
- Confirmation message on click: Er du sikker på at du vil purre alle som ikke har status "match"?

**Comment by alkemann** [comment]
https://docs.google.com/document/d/1Kt9J0j87HuikIE_vnmvoBKoI5P5mWHRSqHLaGXreC_4/edit

**Comment by alkemann** [comment]
please test
